services:
  postgres:
    image: postgres:16-alpine
    container_name: requerimientos_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: root
      POSTGRES_DB: DB_REQUERIMIENTOS_V1
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sa -d DB_REQUERIMIENTOS_V1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
