services:
  postgres:
    image: postgres:16-alpine
    container_name: requerimientos_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: root
      POSTGRES_DB: DB_REQUERIMIENTOS_V1
    ports:
      - "5433:5432"
